server:
  port: 8761
security:
  user:
    name: qhb         #用户名
    password: 123456  #自定义密码
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/