server:
  port: 6000

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://qhb:123456@localhost:8761/eureka/


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invest?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: qazwsx123
  redis:
    host: 127.0.0.1
    port: 6379
    database: 5